POST http://localhost:8080/api/applications/sync?max=200
Accept: application/json

###
GET http://localhost:8080/api/applications
Accept: application/json

###
GET http://localhost:8080/api/applications/stats/funnel
Accept: application/json

###
GET http://localhost:8080/api/applications/7
Accept: application/json

###
POST http://localhost:8000/classify
Content-Type: application/json
{
  "sender": "Ramp Talent Team <no-reply@ashbyhq.com>",
  "subject": "Update on your application to Ramp",
  "snippet": "PASTE_SNIPPET_HERE"
}

###
POST http://localhost:8080/api/gmail/correct
Content-Type: application/json

{
"messageId": "1a0eeaeb48f2e290",
"label": "rejection"
}

###
GET http://localhost:8080/api/applications/stats/funnel

###
POST http://localhost:8000/understand
Content-Type: application/json

{"sender": "Ramp Talent Team <no-reply@ashbyhq.com>", "subject": "Ramp | Confirmation on your Application + CodeSignal", "snippet": "Hi Abdelrahman, Thank you for taking the time to apply to our Software Engineer opening at Ramp! Your application has been received and will be reviewed as soon as you complete the CodeSignal"}
